title: Mayor's Innovation Challenge Data Portal
author: Centre for Advanced Computing
facebook: https://www.facebook.com/TheCityOfKingston
twitter: https://twitter.com/cityofkingston
youtube: https://www.youtube.com/user/TheCityofKingston
